export const REQUEST_CONTACTS = 'REQUEST_CONTACTS::Contacts';
export const REQUEST_CONTACTS_SUCCESS = 'REQUEST_CONTACTS_SUCCESS::Contacts';
export const REQUEST_CONTACTS_ERROR = 'REQUEST_CONTACTS_ERROR::Contacts';
