export const REQUEST_CONTACTS = 'REQUEST_CONTACTS::Contacts';
export const REQUEST_CONTACTS_SUCCESS = 'REQUEST_CONTACTS_SUCCESS::Contacts';
export const REQUEST_CONTACTS_ERROR = 'REQUEST_CONTACTS_ERROR::Contacts';
export const SELECT_CONTACT_BY_ID = 'SELECT_CONTACT_BY_ID::Contacts';
export const EDIT_CONTACT = 'EDIT_CONTACT::Contacts';
export const EDIT_CONTACT_SUCCESS = 'EDIT_CONTACT_SUCCESS::Contacts';
